import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    'quick_start',
    'markdown',
    {
      type: 'category',
      label: 'Основа',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'basics',
        },
      ],
    },
    {
      type: 'category',
      label: 'Компоненты',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Компоненты форм',
          link: {
            type: 'doc',
            id: 'components/forms/forms-introduction',
          },
          items: ['components/forms/input'],
        },
      ],
    },
  ],
};

export default sidebars;
